/*
 * FloppyConstants.h - Constants for floppy disk operations
 */

#ifndef FLOPPYCONSTANTS_H
#define FLOPPYCONSTANTS_H

// Floppy disk constants
#define FLOPPY_SECTOR_SIZE 512
#define FLOPPY_TRACKS 80
#define FLOPPY_HEADS 2
#define FLOPPY_SECTORS_PER_TRACK 18
#define FLOPPY_TOTAL_SECTORS (FLOPPY_TRACKS * FLOPPY_HEADS * FLOPPY_SECTORS_PER_TRACK)  // 2880 sectors
#define FLOPPY_DISK_SIZE (FLOPPY_TOTAL_SECTORS * FLOPPY_SECTOR_SIZE)  // 1474560 bytes (1.44MB)

// Floppy controller I/O ports
#define FDC_BASE_PORT 0x3F0
#define FDC_STATUS_REG_A 0x3F0
#define FDC_STATUS_REG_B 0x3F1
#define FDC_DIGITAL_OUTPUT_REG 0x3F2
#define FDC_TAPE_DRIVE_REG 0x3F3
#define FDC_MAIN_STATUS_REG 0x3F4
#define FDC_DATARATE_SELECT_REG 0x3F4
#define FDC_DATA_FIFO 0x3F5
#define FDC_DIGITAL_INPUT_REG 0x3F7
#define FDC_CONFIG_CONTROL_REG 0x3F7

// Floppy controller commands
#define FDC_CMD_READ_TRACK 0x02
#define FDC_CMD_SPECIFY 0x03
#define FDC_CMD_SENSE_DRIVE_STATUS 0x04
#define FDC_CMD_WRITE_DATA 0x05
#define FDC_CMD_READ_DATA 0x06
#define FDC_CMD_RECALIBRATE 0x07
#define FDC_CMD_SENSE_INTERRUPT 0x08
#define FDC_CMD_WRITE_DELETED_DATA 0x09
#define FDC_CMD_READ_ID 0x0A
#define FDC_CMD_READ_DELETED_DATA 0x0C
#define FDC_CMD_FORMAT_TRACK 0x0D
#define FDC_CMD_DUMPREG 0x0E
#define FDC_CMD_SEEK 0x0F
#define FDC_CMD_VERSION 0x10
#define FDC_CMD_SCAN_EQUAL 0x11
#define FDC_CMD_PERPENDICULAR_MODE 0x12
#define FDC_CMD_CONFIGURE 0x13
#define FDC_CMD_UNLOCK 0x14
#define FDC_CMD_LOCK 0x94
#define FDC_CMD_VERIFY 0x16
#define FDC_CMD_SCAN_LOW_OR_EQUAL 0x19
#define FDC_CMD_SCAN_HIGH_OR_EQUAL 0x1D

// Floppy controller status bits
#define FDC_STATUS_BUSY 0x10
#define FDC_STATUS_DMA 0x20
#define FDC_STATUS_DIRECTION 0x40
#define FDC_STATUS_READY 0x80

// Floppy drive types
enum FloppyDriveType {
    FLOPPY_DRIVE_NONE = 0,
    FLOPPY_DRIVE_360KB_525 = 1,
    FLOPPY_DRIVE_12MB_525 = 2,
    FLOPPY_DRIVE_720KB_35 = 3,
    FLOPPY_DRIVE_144MB_35 = 4,
    FLOPPY_DRIVE_288MB_35 = 5
};

#endif // FLOPPYCONSTANTS_H